<?php
    $this->form->prepare();

    $this->form->setAttribute('method', 'POST');
    $this->form->setAttribute('action', $this->url('home'));
?>


<div>
<?php foreach($this->entries as $entry): ?>
  <div>
    <?php if ($entry->getName()): ?>
      <h3><?= $entry->getName() ?></h3>
    <?php endif ?>
    <?php if ($entry->getEmail()): ?>
      <small><?= $entry->getEmail() ?></small>
    <?php endif ?>
    <p><?= $entry->getContent() ?></p>
  </div>
<?php endforeach; ?>
</div>

<?= $this->form()->openTag($this->form) ?>
<div class="form-group">
    <?= $this->formLabel($this->form->get('name')) ?>
    <?= $this->formElementErrors($this->form->get('name')); ?>
    <?= $this->formTextarea($this->form->get('name')->setAttribute('class', 'form-control')) ?>
    <?= $this->formLabel($this->form->get('email')) ?>
    <?= $this->formElementErrors($this->form->get('email')); ?>
    <?= $this->formTextarea($this->form->get('email')->setAttribute('class', 'form-control')) ?>
    <?= $this->formLabel($this->form->get('content')) ?>
    <?= $this->formElementErrors($this->form->get('content')); ?>
    <?= $this->formTextarea($this->form->get('content')->setAttribute('class', 'form-control')) ?>
</div>

<?= $this->formSubmit($this->form->get('submit')->setAttribute('class', 'btn btn-primary')) ?>

<?= $this->form()->closeTag($this->form) ?>
