<?php
    $this->form->prepare();

    $this->form->setAttribute('method', 'POST');
    $this->form->setAttribute('action', $this->url('home'));
?>


<div>
<?php foreach($this->entries as $entry): ?>
<p><?= $entry->getContent() ?></p>
<?php endforeach; ?>
</div>

<?= $this->form()->openTag($this->form) ?>
<div class="form-group">
    <?= $this->formLabel($this->form->get('content')) ?>
    <?= $this->formElementErrors($this->form->get('content')); ?>
    <?= $this->formTextarea($this->form->get('content')->setAttribute('class', 'form-control')) ?>
</div>

<?= $this->formSubmit($this->form->get('submit')->setAttribute('class', 'btn btn-primary')) ?>

<?= $this->form()->closeTag($this->form) ?>
